# Generated by Django 5.2.10 on 2026-01-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drawing_server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
