# Generated by Django 5.2.10 on 2026-02-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drawing_server", "0004_tasklog_result_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="excel_file_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
